import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen">
          <aside className='w-72 bg-indigo-700'>
            <nav className='p-4'>
              <h1 className='text-white text-2xl font-bold'>Tracking System</h1>
              <ul className='mt-4 space-y-2'>
                <li>
                  <Link href='/' className='text-white'>Dashboard</Link>
                </li>
                <li>
                  <Link href='/projects/' className='text-white'>Projects</Link>
                </li>
                <li>
                  <Link href='/users' className='text-white'>Users</Link>
                </li>
                
              </ul>
            </nav>
          </aside>
          <div className='grow flex flex-col h-screen'>
            <nav className='p-4 bg-gray-100 h-14 border-b'>

            </nav>
            <div className='grow overflow-y-scroll'>
              {children}
            </div>
            
            <footer className='px-4 py-3 bg-gray-100 border-t shadow-slate-200'>
              All right reserved
            </footer>
          </div>
        </main>
      </body>
    </html>
  )
}
