import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen">
          <aside className='w-72 bg-indigo-700'>
            <nav className='p-4'>
              <h1 className='text-white text-2xl font-bold'>Tracking System</h1>
              <ul className='mt-4 space-y-2'>
                <li>
                  <a href='#' className='text-white'>Dashboard</a>
                </li>
                <li>
                  <a href='#' className='text-white'>Users</a>
                </li>
              </ul>
            </nav>
          </aside>
          <div className='grow flex flex-col h-screen'>
            <nav className='p-4 bg-gray-100 h-14 border-b'>

            </nav>
            <div className='grow'>
              {children}
            </div>
            
            <footer className='p-4 bg-gray-100 border-t h-11'>
              All right reserved
            </footer>
          </div>
        </main>
      </body>
    </html>
  )
}
